In [1]:
import numpy as np

In [2]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [3]:
ar = np.ones(10)
ar

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
u = np.arange(1,56,3)
u

array([ 1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
 52, 55])

In [6]:
k = np.linspace(0,10,num=5)
k

array([ 0. , 2.5, 5. , 7.5, 10. ])

In [9]:
lista = np.array([23,7,8,9,12,15,0,-77,78,99,-1,0,56,235,8])
lista

array([ 23, 7, 8, 9, 12, 15, 0, -77, 78, 99, -1, 0, 56,
 235, 8])

In [10]:
print(type(lista))

<class 'numpy.ndarray'>


In [11]:
print(lista[7])

-77


In [12]:
print(lista[2:6])

[ 8  9 12 15]


In [13]:
print(lista[4:])

[ 12  15   0 -77  78  99  -1   0  56 235   8]


In [14]:
print(lista[:7])

[23  7  8  9 12 15  0]


In [15]:
print(lista[:len(lista)-2])

[ 23   7   8   9  12  15   0 -77  78  99  -1   0  56]


In [16]:
print(lista[1::2])

[  7   9  15 -77  99   0 235]


In [17]:
print(lista[::-1])

[  8 235  56   0  -1  99  78 -77   0  15  12   9   8   7  23]


In [18]:
#macierz wartości
w = np.array([[1,2,4,5],[8,7,6,11],[12,18,20,23]])
w

array([[ 1, 2, 4, 5],
 [ 8, 7, 6, 11],
 [12, 18, 20, 23]])

In [19]:
ln = list([[1,2,4,5],[8,7,6,11],[12,18,20,23]])
ln

[[1, 2, 4, 5], [8, 7, 6, 11], [12, 18, 20, 23]]

In [20]:
print(w[w<5])

[1 2 4]


In [21]:
pc = (w>=5)
print(w[pc])

[ 5  8  7  6 11 12 18 20 23]


In [22]:
pr = w[w%2==0]
print(pr)

[ 2  4  8  6 12 18 20]


In [23]:
c= w[(w>2) & (w<=15)]
print(c)

[ 4  5  8  7  6 11 12]


In [24]:
v = w[(w<=7) | (w>20)]
print(v)

[ 1  2  4  5  7  6 23]


In [25]:
lt = np.arange(1,25)
lt

array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
 18, 19, 20, 21, 22, 23, 24])

In [33]:
mt = lt.reshape(4,6)
mt

array([[ 1, 2, 3, 4, 5, 6],
 [ 7, 8, 9, 10, 11, 12],
 [13, 14, 15, 16, 17, 18],
 [19, 20, 21, 22, 23, 24]])

In [34]:
dane = np.array([1,3,7])

In [35]:
ones = np.ones(3,dtype=int)
tw = np.array([2,2,2])

In [36]:
#operacje na macierzach
print(dane+ones)

[2 4 8]


In [37]:
print(dane*tw)

[ 2  6 14]


In [38]:
l1 = [2,3,4]
l2 = [5,6,7]
l = l1+l2
l

[2, 3, 4, 5, 6, 7]

In [39]:
arr = tw+dane
arr

array([3, 5, 9])

In [40]:
print(dane/tw)

[0.5 1.5 3.5]


In [42]:
tr= np.array([4,4,6,6])

In [43]:
print(tr+tw)

ValueError: ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [46]:
print(dane.sum())
print(dane.mean())
print(dane.var()) 

11
3.6666666666666665
6.222222222222222


In [47]:
tab = np.array([[1,8],[23,9]])
tab

array([[ 1, 8],
 [23, 9]])

In [48]:
print(tab.sum(axis=0))
print(tab.sum(axis=1))

[24 17]
[ 9 32]


In [52]:
tab = tab*1.88
tab

array([[ 1.88, 15.04],
 [43.24, 16.92]])

In [53]:
print(tab.max())
print(tab.min())
print(tab.sum())

43.239999999999995
1.88
77.08


In [54]:
from io import StringIO

In [66]:
dane = u"1-2-3\n5-7-83\n240-923-4"

In [65]:
t = np.genfromtxt(StringIO(dane),delimiter="-")
t

array([[ 1., 2., 3.],
 [ 5., 7., 83.],
 [240., 923., 4.]])

In [67]:
dane = u"""#
#komentarz...
1, 2
45, 7
67, 1 #trzecia linia
9, 3
#pusta linia
10, 0
"""

In [70]:
p = np.genfromtxt(StringIO(dane),comments="#", delimiter=",")
p

array([[ 1., 2.],
 [45., 7.],
 [67., 1.],
 [ 9., 3.],
 [10., 0.]])