In [1]:
import tensorflow as tf
print(f"wersja tf: {tf.__version__}")

wersja tf: 2.7.0


In [25]:
#przygotowanie zbioru danych
mnist = tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

In [26]:
#sieć neuronowa - budowa modelu
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [27]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.24195978, -0.21595345, 0.09328096, 0.60022914, -0.2763626 ,
 0.11664651, -0.09990728, 0.64926416, 0.4030193 , 0.35127842]],
 dtype=float32)

In [28]:
tf.nn.softmax(predictions).numpy()

array([[0.10094366, 0.0638572 , 0.08699789, 0.14443535, 0.06011385,
 0.08905458, 0.07171469, 0.15169425, 0.11858407, 0.11260445]],
 dtype=float32)

In [29]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [30]:
loss_fn(y_train[:1],predictions).numpy()

2.418506

In [31]:
#przygotowanie do treningu:
model.compile(optimizer="adam",loss=loss_fn,metrics=['accuracy'])

In [32]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2944 - accuracy: 0.9138
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1432 - accuracy: 0.9579
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1065 - accuracy: 0.9679
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0854 - accuracy: 0.9733
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0738 - accuracy: 0.9772


In [19]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 0s - loss: 0.0724 - accuracy: 0.9797 - 336ms/epoch - 1ms/step


[0.07240139693021774, 0.9797000288963318]

In [33]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [34]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.3458643e-08, 3.5950830e-08, 1.8004846e-06, 1.8818895e-05,
        5.3451677e-11, 2.6749936e-08, 2.2644198e-13, 9.9997663e-01,
        9.0811156e-08, 2.5580018e-06],
       [1.9057800e-09, 3.4425186e-06, 9.9996412e-01, 5.0223721e-06,
        1.7260488e-17, 2.0538298e-05, 1.5874118e-08, 2.5668666e-16,
        6.9044972e-06, 1.5344261e-11],
       [1.9849128e-06, 9.9927324e-01, 9.1658854e-05, 9.9880290e-06,
        1.1801729e-05, 7.7898731e-06, 2.4515863e-05, 4.3402225e-04,
        1.4248281e-04, 2.6475539e-06],
       [9.9998486e-01, 8.7698254e-10, 1.3388869e-06, 9.8112821e-08,
        1.2232098e-09, 1.5007004e-07, 1.2169407e-05, 1.0854731e-06,
        6.0836051e-11, 3.1877659e-07],
       [3.2416654e-05, 3.7463623e-09, 5.2813491e-05, 1.3918741e-07,
        9.9118376e-01, 8.3550249e-06, 1.2256691e-04, 9.2041283e-04,
        1.9000439e-05, 7.6605449e-03]], dtype=float32)>